# Generated by Django 5.2.1 on 2025-06-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queries", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="querydefinition",
            name="schedule_frequency",
        ),
        migrations.RemoveField(
            model_name="querydefinition",
            name="schedule_start_datetime",
        ),
        migrations.AddField(
            model_name="querydefinition",
            name="schedule_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
