# Generated by Django 5.2.1 on 2025-06-21 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="queryrunresult",
            options={"ordering": ["-executed_at"]},
        ),
        migrations.RemoveField(
            model_name="queryrunresult",
            name="expires_at",
        ),
        migrations.AddField(
            model_name="queryrunresult",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queryrunresult",
            name="result_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queryrunresult",
            name="result_output_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="queryrunresult",
            name="result_rows_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queryrunresult",
            name="result_storage_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="queryrunresult",
            name="triggered_by",
            field=models.CharField(default="MANUAL", max_length=100),
        ),
        migrations.AlterField(
            model_name="queryrunresult",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="queryrunresult",
            name="executed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="queryrunresult",
            name="query",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="run_results",
                to="queries.querydefinition",
            ),
        ),
        migrations.AlterField(
            model_name="queryrunresult",
            name="result_data_csv",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="queryrunresult",
            name="status",
            field=models.CharField(default="PENDING", max_length=50),
        ),
    ]
