# Generated by Django 5.2.1 on 2025-06-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queries", "0003_alter_querydefinition_last_successful_run_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="querydefinition",
            name="output_target",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("GOOGLE_SHEET", "Google Sheets"),
                    ("LOOKER_STUDIO", "Google Looker Studio"),
                ],
                default="NONE",
                max_length=50,
            ),
        ),
    ]
