# Generated by Django 5.2.1 on 2025-06-01 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GOOGLE_ADS', 'Google Ads'), ('YOUTUBE_CHANNEL', 'YouTube Channel'), ('GOOGLE_PLAY', 'Google Play'), ('GOOGLE_AD_MANAGER', 'Google Ad Manager'), ('FACEBOOK_ADS', 'Facebook Ads')], max_length=50, unique=True)),
                ('display_name', models.CharField(default='Default Name', max_length=255)),
                ('oauth_required', models.BooleanField(default=True)),
                ('required_scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('target_dataset_id', models.CharField(max_length=200)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(blank=True, help_text='關聯的社交帳號用於 OAuth', null=True, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connections.datasource')),
            ],
            options={
                'unique_together': {('user', 'data_source', 'display_name')},
            },
        ),
    ]
