# Generated by Django 5.2.1 on 2025-06-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0002_add_facebook_data_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="dts_transfer_config_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="connection",
            name="last_sync_status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connection",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_DTS_SETUP", "Pending DTS Setup"),
                    ("ACTIVE", "Active"),
                    ("ERROR", "Error"),
                    ("INACTIVE", "Inactive"),
                ],
                default="PENDING_DTS_SETUP",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="name",
            field=models.CharField(
                choices=[
                    ("GOOGLE_ADS", "Google Ads"),
                    ("YOUTUBE_CHANNEL", "YouTube Channel"),
                    ("GOOGLE_PLAY", "Google Play"),
                    ("GOOGLE_AD_MANAGER", "Google Ad Manager"),
                    ("FACEBOOK", "Facebook Ads"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
