# Generated by Django 5.2.1 on 2025-06-03 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_google_social_account_client_oauth_status"),
        ("connections", "0003_connection_dts_transfer_config_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.client",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("ERROR", "Error"),
                    ("INACTIVE", "Inactive"),
                ],
                default="PENDING_DTS_SETUP",
                max_length=20,
            ),
        ),
    ]
