# Generated by Django 5.2.1 on 2025-06-07 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0005_alter_datasource_name"),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connection",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="last_sync",
        ),
        migrations.AddField(
            model_name="connection",
            name="last_sync_record_count",
            field=models.IntegerField(
                blank=True,
                help_text="The number of records fetched in the last successful sync.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="last_sync_time",
            field=models.DateTimeField(
                blank=True,
                help_text="The timestamp of the last sync attempt.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="last_sync_status",
            field=models.TextField(
                blank=True,
                help_text="A message describing the result of the last sync (e.g., SUCCESS, or the error message).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                help_text="關聯的社交帳號用於 OAuth",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="socialaccount.socialaccount",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("SYNCING", "Syncing"),
                    ("ERROR", "Error"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
