# Generated by Django 5.2.1 on 2025-06-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0006_remove_connection_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAdsField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="完整的 API 欄位名稱，例如 'metrics.clicks'",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="顯示在 UI 上的名稱，例如 'Clicks'", max_length=255
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ATTRIBUTE", "Attribute"),
                            ("METRIC", "Metric"),
                            ("SEGMENT", "Segment"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("data_type", models.CharField(max_length=50)),
                ("is_selectable", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Google Ads Field",
                "verbose_name_plural": "Google Ads Fields",
                "ordering": ["category", "display_name"],
            },
        ),
    ]
