# Generated by Django 5.2.1 on 2025-06-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0007_googleadsfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="googleadsfield",
            name="group",
            field=models.CharField(
                blank=True,
                help_text="User-friendly group name",
                max_length=50,
                null=True,
            ),
        ),
    ]
