# Generated by Django 5.2.1 on 2025-06-09 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0008_googleadsfield_group"),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connection",
            name="dts_transfer_config_name",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="last_sync_record_count",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="last_sync_status",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="last_sync_time",
        ),
        migrations.AddField(
            model_name="connection",
            name="is_enabled",
            field=models.BooleanField(
                default=True, help_text="控制此連線的排程是否啟用 (On/Off)"
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Only set if the data source requires OAuth authentication.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="socialaccount.socialaccount",
            ),
        ),
        migrations.AlterField(
            model_name="googleadsfield",
            name="display_name",
            field=models.CharField(
                help_text="UI display name, e.g. 'Clicks'", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="googleadsfield",
            name="field_name",
            field=models.CharField(
                help_text="Full API field name, e.g. 'metrics.clicks'",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="ConnectionExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_method",
                    models.CharField(
                        choices=[("SYSTEM", "System"), ("MANUAL", "Manual")],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, help_text="Result message", null=True),
                ),
                (
                    "record_count",
                    models.IntegerField(
                        blank=True, help_text="Sync record count", null=True
                    ),
                ),
                (
                    "config_snapshot",
                    models.JSONField(
                        help_text="Connection config at the time of execution"
                    ),
                ),
                (
                    "display_name_snapshot",
                    models.CharField(
                        help_text="Display name at the time of execution",
                        max_length=200,
                    ),
                ),
                (
                    "target_dataset_id_snapshot",
                    models.CharField(
                        help_text="Target dataset ID at the time of execution",
                        max_length=200,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Task start time"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, help_text="Task finish time", null=True
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="connections.connection",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="If the task was triggered by a user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Connection Execution",
                "verbose_name_plural": "Connection Executions",
                "ordering": ["-started_at"],
            },
        ),
    ]
