# Generated by Django 5.2.1 on 2025-06-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0009_remove_connection_dts_transfer_config_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="googleadsfield",
            name="compatible_fields",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="connections.googleadsfield"
            ),
        ),
    ]
