# Generated by Django 5.2.1 on 2025-06-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_clientsocialaccount"),
    ]

    operations = []
