# Generated by Django 5.2.1 on 2025-06-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_link_existing_social_accounts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="facebook_oauth_status",
        ),
        migrations.RemoveField(
            model_name="client",
            name="facebook_social_account",
        ),
        migrations.RemoveField(
            model_name="client",
            name="google_social_account",
        ),
        migrations.RemoveField(
            model_name="client",
            name="oauth_status",
        ),
    ]
