# Generated by Django 5.2.1 on 2025-06-02 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="google_social_account",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"provider": "google"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="socialaccount.socialaccount",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="oauth_status",
            field=models.CharField(
                choices=[
                    ("NOT_AUTHORIZED", "Not Authorized"),
                    ("AUTHORIZED", "Authorized"),
                ],
                default="NOT_AUTHORIZED",
                max_length=20,
            ),
        ),
    ]
