# Generated by Django 5.2.1 on 2025-06-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_google_social_account_client_oauth_status"),
    ]

    operations = []
