# Generated by Django 5.2.1 on 2025-06-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_add_facebook_oauth_fields"),
    ]

    operations = []
