# Generated by Django 5.2.1 on 2025-06-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookAdsField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The internal name of the Facebook Ads field.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The display label of the Facebook Ads field.",
                        max_length=255,
                    ),
                ),
                (
                    "insights_level",
                    models.CharField(
                        help_text="The insights level this field belongs to (e.g., 'campaign', 'ad_set', 'ad').",
                        max_length=50,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        help_text="Type of field: 'breakdown', 'action_breakdown', or 'field'.",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Facebook Ads Field",
                "verbose_name_plural": "Facebook Ads Fields",
                "unique_together": {("name", "insights_level")},
            },
        ),
    ]
