# Generated by Django 5.2.1 on 2025-06-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0002_facebookadsfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facebookadsfield",
            name="name",
            field=models.CharField(
                help_text="The internal name of the Facebook Ads field.", max_length=255
            ),
        ),
    ]
