# Generated by Django 5.2.1 on 2025-06-25 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0003_alter_facebookadsfield_name"),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                help_text="The social account used for this connection.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="socialaccount.socialaccount",
            ),
        ),
    ]
