# Generated by Django 5.2.1 on 2025-06-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0004_connection_client_alter_connection_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="name",
            field=models.CharField(
                choices=[
                    ("GOOGLE_ADS", "Google Ads"),
                    ("FACEBOOK_ADS", "Facebook Ads"),
                    ("GOOGLE_SHEET", "Google Sheet"),
                    ("CSV", "CSV File"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
