# Generated by Django 5.2.1 on 2025-06-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0010_googleadsfield_compatible_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="required_scopes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
